### ISSUE TITLE
could not get this to work in my app... :(

### ISSUE THREAD

**Issue by paulpreibisch** [FauzanKhan/angular-popover#3]
Hi there, are you using a specific version of jquery or angular?

I tried the demo app and it worked, however, I could not get it to work in my app,

doesn't hide what's inside of the <ng-popover> directive

**Comment by FauzanKhan** [comment]
Hi @paulpreibisch 

I built the directive on Angular 1.3, the demo is using Angular 1.4 and I think it should work fine on Angular 1.X In case you are getting any error in the console, can you share it with me so that, I can investigate it further.

**Comment by paulpreibisch** [comment]
unfortunately, I am stuck with angular 1.3.1 at the moment.  There were no errors in the console, for some reason the css failed to apply no mater what I did...

**Comment by FauzanKhan** [comment]
Are you sure you're loading the compiled CSS fie and not the SASS file? If you're not using SASS in your project then you'll need to use [this](https://github.com/FauzanKhan/angular-popover/blob/master/dist/css/demo.css) file instead of the `.scss` file in the `src` folder. Please note the `.css` extension of the file.
